theme = "github.com/jpanther/lynx"
title = "Jordan Felle"

enableEmoji = true
disableKinds = ["taxonomy", "term"]

[params.author]
  name = "Jordan Felle"
  headline = ""
  image = "author.jpg"
  links = [
    { camera = { href = "https://photo.felle.me", text = "Photography", icon = "camera" } },
    { telegram = "https://t.me/jordanfelle" },
    { github = "https://github.com/jordanfelle" },
    { facebook = "https://www.facebook.com/hyper123" },
    { instagram = "https://www.instagram.com/hyper123" },
    { lastfm = "https://www.last.fm/user/hyper123123" },
    { linkedin = "https://www.linkedin.com/in/jordanfelle" },
    { steam = "https://steamcommunity.com/id/hyper123" },
    { trakt = { href = "https://trakt.tv/users/hyper123", text = "Trakt", icon = "trakt" } },
  ]

[markup.highlight]
  noClasses = false

[markup.goldmark]
[markup.goldmark.renderer]
  unsafe = true
